# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.sms.at:
  peer0.aws.sms.at:
  peer0.azure.sms.at:
  peer0.univie.sms.at:

networks:
  sms:

services:
  orderer.sms.at:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.sms.at
    container_name: orderer.sms.at
    networks:
      - sms

  peer0.aws.sms.at:
    container_name: peer0.aws.sms.at
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.aws.sms.at
    networks:
      - sms

  peer0.azure.sms.at:
    container_name: peer0.azure.sms.at
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.azure.sms.at
    networks:
      - sms

  peer0.univie.sms.at:
    container_name: peer0.univie.sms.at
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.univie.sms.at
    networks:
      - sms

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.aws.sms.at:7051
      - CORE_PEER_LOCALMSPID=AwsMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/aws.sms.at/peers/peer0.aws.sms.at/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/aws.sms.at/peers/peer0.aws.sms.at/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/aws.sms.at/peers/peer0.aws.sms.at/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/aws.sms.at/users/Admin@aws.sms.at/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.sms.at
      - peer0.aws.sms.at
      - peer0.azure.sms.at
      - peer0.univie.sms.at
    networks:
      - sms
